### PR TITLE
Fix RSDPDescriptor Mistake

### PR DESCRIPTION
**Pull request by maxtyson123**
I notice that you say:
• Signature: Is an 8 byte string, that must contain: “RSDT PTR” P.S. The string is not null
terminated

Where it should be “RSD PTR "
[Ref: OSDev Wiki](https://wiki.osdev.org/RSDP#:~:text=This%208%2Dbyte%20string%20(not%20null%20terminated!)%20must%20contain%20%22RSD%20PTR%20%22.%20It%20stands%20on%20a%2016%2Dbyte%20boundary.)

image

### CODE REVIEW

**Comment by DeanoBurrito** [comment]
Lgtm, thanks for the fix! Feel free to add yourself to the list in `99_Appendices/I_Acknowledgements.md` if you want, you can push the change to this PR. If not let us and know we'll merge it. 

Btw it may be more valuable to quote the acpi spec (where the magic value is defined) as the source rather than a publicly editable wiki.

**Comment by maxtyson123** [comment]
Added Acknowledgement, the updated refrence is here: https://uefi.org/sites/default/files/resources/ACPI_1.pdf#page=91

**Comment by DeanoBurrito** [comment]
Cool! Just check your acknowledgement entry again, you only changed one of the profile links (one still links to the previous person on that list).

**Comment by maxtyson123** [comment]
Good spotting, all done now

**Comment by DeanoBurrito** [comment]
It's why we review PRs 😉
Thanks again for the fix, merged this one.

**Pull request merged**
